version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./api/db/script.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - forum-net

  api:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: forum
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - forum-net

  thread:
    build: ./thread
    ports:
      - "80:3000"
    depends_on:
      - api
    networks:
      - forum-net

  sender:
    build: ./sender
    ports:
      - "8080:3000"
    depends_on:
      - api
    networks:
      - forum-net

networks:
  forum-net:
    driver: bridge

volumes:
  db_data:
