name: Lint all services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, thread, sender]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies ({{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: Run ESLint ({{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm run lint

      - name: Run Tests ({{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm test
