name: Lint all services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix: { service: [api, thread, sender] }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: '18' }
      - name: Install (${{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm ci
      - name: Lint (${{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm run lint
      - name: Test (${{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm test

  docker:
    runs-on: ubuntu-latest
    needs: eslint
    if: github.event_name == 'push'
    strategy:
      matrix: { service: [api, thread, sender] }
    steps:
      - uses: actions/checkout@v3

      - name: Login GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & Push
        env:
          SERVICE: ${{ matrix.service }}
          OWNER: ${{ github.repository_owner }}
          TAG: ${{ steps.vars.outputs.sha_short }}
        run: |
          IMAGE="ghcr.io/${OWNER}/forum-anonyme-${SERVICE}:${TAG}"
          docker build -t "$IMAGE" "$SERVICE"
          docker push "$IMAGE"
