name: Lint all services

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, thread, sender]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies ({{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm ci

      - name: Run ESLint ({{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm run lint

      - name: Run Tests ({{ matrix.service }})
        working-directory: ${{ matrix.service }}
        run: npm test
        
  docker:
    runs-on: ubuntu-latest
    needs: eslint
    strategy:
      matrix:
        service: [api, thread, sender]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/$SERVICE:${{ steps.vars.outputs.sha_short }} $SERVICE
        env:
          SERVICE: ${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/$SERVICE:${{ steps.vars.outputs.sha_short }}
        env:
          SERVICE: ${{ matrix.service }}


