name: Lint API

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      runs:
        working-directory: api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
